---
title: "The Probabilistic Analysis CHECK R package"
author: "X. Pouwels & H. Koffijberg"
date: "`r Sys.Date()`"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction
Health economic models are routinely develop to inform health policy decisions such as including (new) healthcare interventions in insurance packages or restricting their use to specific subgroups **[REF]**. Validating health economic models is an important step during the development of health economic models, as it contributes to prove their credibility **[REF CARO]**.\
Currently, two guidelines have been developed to standardise the validation of health economic models: the AdviSHE tool and the TECH-VER checklist **[REFs]**. The former considers all relevant aspects of health economic model validation from the face validity of the conceptual model toexternal validity of the model structure, inputs and outputs, while the latter focuses on the technical verification of health economic models. Even though both guidelines provide thorough frameworks to validate health economic models, their use is not compulsory when submitting health economic models to scientific journals or to health technology agencies, which takes formulary decisions. Besides the formal implementation of these guidelines in regulatory and publishing workflows, their use may be limited due to their lack of practicality, i.e. both guidelines are solely described in a scientific journal article and needs copy-pasting to be filled in.\
To overcome this lack of practicality of current validation guidelines, we have developed the R package *pacheck*  (probabilistic analysis check). *Pacheck* contains a suite of functions to systematically validate and explore health economic models using the probabilistic inputs and outputs of health economic models. We decided to focus on the vlaidation of probabilistic inputs and outputs since health economic models are not routinely published open source. Hence, *pacheck* allows to partly validate health economic models without requiring access to the original health economic model. This manuscript describes the functionalities of *pacheck*.\

# Functionalities

